### ISSUE TITLE
Help with ordering a build kit for  MPCNC

### ISSUE THREAD

**Issue by tansohn** [V1EngineeringInc/MPCNC_Primo_Tool_Mounts#3]
I am wanting to build a  MPCNC system.  My intent is to build the working space 48"X 24".

Looking t the calculator I am not sure if the belts are as follows

Length (inches) | Qty | Name
-- | -- | --
6 | 1 | leadscrew length
62 | 2 | belt length along x
38.25 | 2 | belt length along y
200.5 | total length | belts (all 4)

Do I order a 4 meters extra ?

Also,  would the kit already include the additional mid support?  i do not see it as an option.

Thanks

**Comment by V1EngineeringInc** [comment]
You need 5.08 meters total so order 6 meters or if you buy a kit add 3 extra meters.

Please use the forums of the contact page for building questions.

**Comment by tansohn** [comment]
Thank you.  I did not meant to post in the wrong forum.

**Comment by V1EngineeringInc** [comment]
No problem, just letting you know the better/faster place to ask questions.
