### ISSUE TITLE
Inconsistent Makita Bottom Mount Model

### ISSUE THREAD

**Issue by Gamogamer** [V1EngineeringInc/MPCNC_Primo_Tool_Mounts#6]
I printed the STLs for the Makita a while ago and now I wanted to design something for dust collection so I downloaded the Step File. After finishing this design I noticed something was wrong. The Models are different between the STP and STL!
This image shows both files in PrusaSlicer for comparison. 

![image](https://user-images.githubusercontent.com/7470667/133666642-8c55291d-16a6-439c-8622-e518ef5f6f52.png)
(Ignore the missing chamfers, needed them gone for some editing)

The pics you uploaded seem to show the STL Version

The main difference is the spacing between the rings since the lower one is now higher.  This leads to the tools machined shaft section sticking out at the top a bit, since it's now mounted higher if flush at the bottom. Conversely this also now means that the spindle sits higher, technically increasing workable Z height.

Not sure which one is strictly speaking better, but having both but not mentioning it is kinda annoying now since I have to redesign some stuff.

**Comment by V1EngineeringInc** [comment]
Are you sure that is not the top and bottom parts?

**Comment by Gamogamer** [comment]
The Top is just a ring without the extension in the Z
![image](https://user-images.githubusercontent.com/7470667/133668593-caebfbf9-0246-40b3-a826-d6a29a9a3336.png)

**Comment by V1EngineeringInc** [comment]
No idea why they were different I added a new step.
